{% set name = "mget3" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mget3-{{ version }}.tar.gz
  sha256: 82ec418dc927356d22e13bedc6497d9a299e1114a873ebc2ab345df3be61371f

build:
  # Our main reason for releasing mget3 on conda-forge is to support users of
  # ArcGIS Pro 3.2.2 and later. ArcGIS Pro 3.2.2 includes Anaconda Python 3.9
  # or later and only runs on Windows. So we're skipping Python < 3.9. We're
  # skipping osx because we don't have Mac hardware or expertise so cannot
  # maintain it, but we'll enable it if a Mac maintainer joins the project.
  skip: true  # [py<39 or py>=314 or py2k or osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - git
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - docutils
    - lxml
    - sphobjinv
    - pip
  run:
    - python
    - copernicusmarine
    - docutils
    - gdal
    - lxml
    - netcdf4
    - numpy
    - packaging
    - pandas
    - pyarrow
    - pyhdf
    - pyparsing
    - python-dateutil
    - requests
    - scikit-fmm
    - scipy
    - tzlocal
    # copernicusmarine 2.x can only be installed on numpy 1.24 or later.
    # ArcGIS Pro 3.2 pins numpy at 1.22.4. This means that the most recent
    # version of copernicusmarine that can be installed on an ArcGIS Pro 3.2
    # conda environment is 1.3.0. However, copernicusmarine depends on
    # aiohttp, but does not stipulate which version must be installed. If too
    # new a version is installed, it will fail with
    #
    #     RuntimeError: no running event loop
    #
    # when copernicusmarine uses it. To prevent ArcGIS Pro 3.2 users from
    # encountering this, we pin aiohttp to version 3.9.5 when running on
    # Python 3.9, which is what comes with ArcGIS Pro 3.2.
    - aiohttp ==3.9.5   # [py<310]
    # Similarly, copernicusmarine or its dependencies also requires
    # setuptools, which itself requires packaging. Unfortunately, on ArcGIS
    # Pro 3.2, the arcgispro-py3 environment pins packaging to 21.3 but does
    # not pin setuptools. As a consequence, when copernicusmarine is installed
    # it updates setuptools to the latest version, which requires packaging
    # 24.0 or later, but apparently doesn't declare that dependency. The
    # result is we have packaging 21.3 still installed but a much newer
    # setuptools, which then breaks with:
    #
    #     TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
    #
    # See https://github.com/pypa/setuptools/issues/4483 for more details. To
    # protect ArcGIS Pro 3.2 users from this, we declare our own dependency on
    # setuptools 70.0 when running on Python 3.9. This hack and the one above
    # is less than optimal for non-ArcGIS conda users, but most likely they
    # will run a newer version of Python, in which case these hack will not be
    # used.
    - setuptools ~=70.0   # [py<310]

test:
  imports:
    - GeoEco
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jjrob/MGET
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  license_url: https://github.com/jjrob/MGET/blob/main/LICENSE
  summary: 'Marine Geospatial Ecology Tools: access and manipulate marine ecological and oceanographic data'
  dev_url: https://github.com/jjrob/MGET
  doc_url: https://mget.readthedocs.io

extra:
  recipe-maintainers:
    - jjrob
